# Generated by Django 5.2.7 on 2025-10-17 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sitios',
            fields=[
                ('sitioId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('username', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimplePassword',
            fields=[
                ('passwordId', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='vault.sitios')),
            ],
        ),
        migrations.CreateModel(
            name='Biometria',
            fields=[
                ('bioId', models.AutoField(primary_key=True, serialize=False)),
                ('embedding', models.JSONField()),
                ('sitio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometria', to='vault.sitios')),
            ],
        ),
    ]
