# Generated by Django 5.2.7 on 2025-11-06 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometria',
            name='sitio',
        ),
        migrations.AddField(
            model_name='biometria',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='biometrias', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitios',
            name='biometrias',
            field=models.ManyToManyField(blank=True, related_name='sitios', to='vault.biometria'),
        ),
    ]
