# Generated by Django 5.2.7 on 2025-11-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_remove_biometria_sitio_biometria_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometria',
            name='name',
            field=models.CharField(default='Cambiar Uwu', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
