# Generated by Django 5.2.7 on 2025-11-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_biometria_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometria',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
